iiddaa96/Netflix-2.0

- app/components/Favourites.tsx
- app/components/Footer.tsx
- app/components/Header.tsx
- app/components/Trending.tsx
- app/page.tsx
La till routing för våra filer
Skapade mappar med de filer vi ska använda oss utav i vårat projekt
> Added routing for our files and basic div

- app/components/Footer.tsx
- app/components/Header.tsx
Implementerade struktur för footer från mui
Samt style lite i footer
> implementerade footer från mui samt satt styleing

- app/Data/movies.ts
- app/components/Header.tsx
- app/page.tsx
Lagt till tillfällig video på landingPage
Lagt till styling på sidan
Lagt till en heading för filmerna
> 15 lägga till provisorisk youtube video på startsidan ovanför karusellerna

- app/Favorite/page.tsx
- app/components/Favourites.tsx
- app/components/Header.tsx
- app/page.tsx
La till mapp för favorite istället för en komponent
La till en karusell i favorite fast utan trailer filmen
La till länkning för favoriter i headern
> 26 skapa pagetsx fr favorites och lgga in en karusell dr

- app/Data/movies.ts
- app/Favorite/page.tsx
- app/components/Film-view.tsx
- app/context/FavoriteMoviesContext.tsx
- app/layout.tsx
- app/page.tsx
Skapat context för favorit sidan
Sam ett försök till att mappa ut filmerna men inte lyckats.
Merge in senaste main till denna branch, kunde ej återgå till min vanliga main efter det och göra "git pull"
Vet att man inte ska merge in halv färdigt, men har skapat en färdig context.
Maryamo fortsätter på contexten senare
> added context for favourite page, trying to map movies out

- app/Data/movies.ts
- app/page.tsx
La till filmens årtal samt åldersgräns/rating i karusellen
Bytte rating till number o data/movies istället för "R" etc
> 31 Added movie year and rating in carusell card

- app/components/Trending.tsx
- app/page.tsx
Har skapat en karusell för trending som mappar ut endast 10 filmer
Har lagt till trending i page/ MovieList
> Added Trending component in page MovieList

- app/components/Header.tsx
- app/components/Trending.tsx
importerat mui sökfält komponent
Gjort den responsive
add year and rating to trending
> 34 skapa sök flt

- app/components/Header.tsx
- app/components/SearchBar.tsx
add new search component bar and removed muis search bar
add functionality for search bar
> 35 skapa funktion fr sökfältet

- app/Favorite/page.tsx
- app/components/Carousell.tsx
- app/components/Header.tsx
- app/page.tsx
added onclick function to show clicked movies in favorite page
> add onclick function to render fav movies in favorite page

- app/Favorite/page.tsx
- app/components/Carousell.tsx
- app/components/Footer.tsx
- app/components/Header.tsx
skapat en grid layout för favorit sida
stylat i footer
bytt ut youtube filen till en nedladdat mp4
> 46 skapa grid och css för favorit sidan

- app/context/FavoriteMoviesContext.tsx
add ls to save favorite movies
> added loclastorage to show favorite movies in page

- app/Favorite/page.tsx
- app/components/Carousell.tsx
- app/components/FavouriteButton.tsx
- app/context/FavoriteMoviesContext.tsx
Har skapat en komponent för hjärt-knappen
Skapat funktion som gör att när du markerar så blir hjärtat hel vit annars border.
Lagt till en marginLeft på korten i karusell komponenten för lite styleing
Ändrat om till att använda favorit-knapp komponenten för karusell sidan
> 50 Skapa en komponent för hjärt-knappen, lägg till knappen på favorit sidan

- app/components/SearchBar.tsx
add functionality for autocomplete and suggestions
> add autocomplete suggestions for search bar

- README.md
Har lagt till text och förklaring i vår readme fil
> Skriv en readme fil

- app/components/FilmView.tsx
La till hjärt-knappen till FilmView filen
> Added favouriteButton to FilmView file

- app/page.tsx
Har satt en loop och tagit bort ljudet på trailern
> Fixa till trailern

- app/components/Carousell.tsx
Ändrat storlek på swipe pilarna så att det blir lite mer synlig
> 54 gr pil knapparna lite strre och mer synliga

- app/components/SearchBar.tsx
removed button so that only one displays movie suggestions
add an empty array to clear search suggestions after movie is clicked
> fixed button and search suggestions

- app/Favorite/page.tsx
- app/context/FavoriteMoviesContext.tsx
Fixade till hydration felet samt lade till en if sats i context för localstorage
> Fixed localStorage error

- app/components/FilmView.tsx
- app/components/SearchBar.tsx
La till marginTop och ändrade gråskalan i FilmView
La till en tom array när man suddar ut text i sökbaren
> 73 Fixa till styleing på knapparna/listan i sökbaren

- app/components/FilmView.tsx
Byte div till Box taggar. 
Bytte img till img component i en box tag för enklare style för mobile
> Fixed FilmView screen for mobile

- .eslintrc.cjs
La till eslint med kod till vårat projekt.
> added eslint to our project
